on:
  # Trigger analysis when pushing in "main" branch. Change this to another branch if you need to
  push:
    branches:
      - main
name: bluemachine gamepad Workflow
jobs:
  tmscan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: bluemachine Scan
        uses: raldozamora/blue-action@main
        with:
          tm_repository_id: 1
          tm_source: hello.sol
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TM_TOKEN_KEY: ${{ secrets.TM_TOKEN_KEY }}
      - name: Upload result
        uses: actions/upload-artifact@v3
        with:
          name: result-report
          path: action_work_result_report.pdf
